// src/models/InferenceLog.js
// Stores one record per LLM API call (not per message).
// This is the core of the observability system.
//
// Schema design decisions:
// - Kept separate from Conversation model because logs have a different
//   lifecycle: you want to query them by time range, model, status, or
//   latency independently of conversation data.
// - inputPreview / outputPreview are truncated at 200 chars and PII-redacted
//   before storage — never store raw user input in logs.
// - piiDetected stores which PII types were found, useful for compliance audits.
// - TTL index (30 days) on createdAt keeps storage bounded without manual cleanup.

import mongoose from "mongoose";

const InferenceLogSchema = new mongoose.Schema(
  {
    // Links back to the conversation
    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Conversation",
      required: true,
      index: true,
    },
    // Unique request identifier (generated by the frontend SDK)
    requestId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    // LLM model used for this specific request
    model: {
      type: String,
      required: true,
    },
    // Provider (anthropic, openai, etc.)
    provider: {
      type: String,
      required: true,
      default: "google",
    },
    // End-to-end latency from request start to last token received (ms)
    latency: {
      type: Number,
      required: true,
    },
    // Token accounting
    inputTokens: {
      type: Number,
      default: 0,
    },
    outputTokens: {
      type: Number,
      default: 0,
    },
    totalTokens: {
      type: Number,
      default: 0,
    },
    // Request outcome
    status: {
      type: String,
      enum: ["success", "error", "cancelled"],
      required: true,
      index: true,
    },
    // Error message if status === "error"
    error: {
      type: String,
      default: null,
    },
    // Short previews for debugging (PII-redacted, max 200 chars)
    inputPreview: {
      type: String,
      maxlength: 200,
    },
    outputPreview: {
      type: String,
      maxlength: 200,
    },
    // Which PII types were detected and redacted
    piiDetected: {
      type: [String],
      default: [],
    },
    // ISO timestamp from the client when the request started
    clientTimestamp: String,
  },
  {
    timestamps: true, // server-side createdAt / updatedAt
    toJSON: { virtuals: true },
  }
);

// TTL index: auto-delete logs older than 30 days
// Remove this if you want to keep all logs forever
InferenceLogSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 30 });

// Compound index for the dashboard query: filter by provider+model, sort by time
InferenceLogSchema.index({ provider: 1, model: 1, createdAt: -1 });

// Virtual: total tokens computed from input + output
InferenceLogSchema.virtual("computedTotalTokens").get(function () {
  return (this.inputTokens || 0) + (this.outputTokens || 0);
});

export default mongoose.model("InferenceLog", InferenceLogSchema);
